name: Publish GradlePlugin

on:
  pull_request:
  push:
    branches:
      - 'github_actions_publish_all'

jobs:
  publish-gradlePlugin:
    #needs: [publish-finalize]
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v2
        with:
          repository: emign/engineEmi_GradlePlugin
          token: ${{ secrets.engineEmiGradlePluginRepoToken }}

      - name: Bump Version Number
        run: |
         touch engineEmiLibVersion.ver
          git config --global user.email "nicolai.emig@amseegym.de"
          git config --global user.name "Nicolai Emig"
          git add engineEmiLibVersion.ver
          git commit -m "Bumped version number"

      - name: Create PR
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.engineEmiGradlePluginRepoToken }}