name: Publish GradlePlugin

on:
  pull_request:
  push:
    branches:
      - 'github_actions_publish_all'

jobs:
  get-version-number:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and retrieve version number
        uses: actions/checkout@v2

      - name: Export Number
        run: |
            export ENGINE_VERSION_NUMBER=$(awk -F '=' '/engineVersion=/{print $2}' gradle.properties)
            echo "::set-env name=ENGINE_VERSION::$ENGINE_VERSION_NUMBER"
            echo "Version2:"
            echo "$ENGINE_VERSION_NUMBER"

      - name: Print Version
        run: |
            echo "Version:"
            echo $ENGINE_VERSION

      - name: Pull GradlePlugin
        uses: actions/checkout@v2
        with:
          repository: emign/engineEmi_GradlePlugin
          token: ${{ secrets.engineEmiGradlePluginRepoToken }}

      - name: Bump Version Number
        run: |
          sed -i 's/^engineVersion=(....)/^engineVersion=$($ENGINE_VERSION)/g' gradle.properties
          echo $ENGINE_VERSION >> engineEmiLibVersion.version
          git config --global user.email "nicolai.emig@amseegym.de"
          git config --global user.name "Nicolai Emig"
          git add engineEmiLibVersion.version
          git add gradle.properties
          git commit -m "Bumped version number"

      - name: Create PR
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.engineEmiGradlePluginRepoToken }}