name: release

on:
  release:
  types: [published]

  jobs:
    build:
      runs-on: [macos-10.15]
      steps:
        - uses: actions/checkout@v1
        - run: ./gradlew release
          env:
            bintrayUser: ${{ secrets.bintrayUser }}
            bintrayApiKey: ${{ secrets.bintrayApiKey }}
            bintrayPassword: ${{ secrets.bintrayPassword }}