name: release

on: [push]

jobs:
  build-mac-jvm:
    runs-on: [macos-10.15]
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew release
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
          bintrayPassword: ${{ secrets.bintrayPassword }}

  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - run: CALL gradlew.bat publishMingwX64PublicationToMavenRepository
        shell: cmd
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
          bintrayPassword: ${{ secrets.bintrayPassword }}
      - run: CALL gradlew.bat --stop
        shell: cmd
