name: release

on:
  push:
    branches:
      - 'master'

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: CALL gradlew.bat --no-daemon jvmTest
        shell: cmd

  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: ./gradlew --no-daemon jvmTest

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: ./gradlew --no-daemon jvmTest

  build-mac:
    needs: [test-mac]
    runs-on: [macos-10.15]
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew publishMacosX64PublicationtoMavenRepository
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
          bintrayPassword: ${{ secrets.bintrayPassword }}
      - run: ./gradlew publishIosArm64PublicationToMavenRepository
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
          bintrayPassword: ${{ secrets.bintrayPassword }}
      - run: ./gradlew publishIosArm32PublicationToMavenRepository
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
          bintrayPassword: ${{ secrets.bintrayPassword }}
      - run: ./gradlew publishIosX64PublicationToMavenRepository
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
          bintrayPassword: ${{ secrets.bintrayPassword }}

  build-windows:
    needs: [test-windows]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - run: CALL gradlew.bat publishMingwX64PublicationToMavenRepository
        shell: cmd
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
          bintrayPassword: ${{ secrets.bintrayPassword }}
      - run: CALL gradlew.bat --stop
        shell: cmd

  build-linux:
    needs: [test-linux]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew publish
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
          bintrayPassword: ${{ secrets.bintrayPassword }}

  publish-finalize:
    needs: [build-windows, build-mac, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew release
        env:
          bintrayUser: ${{ secrets.bintrayUser }}
          bintrayApiKey: ${{ secrets.bintrayApiKey }}
          bintrayPassword: ${{ secrets.bintrayPassword }}

  refresh-version-numbers-on-repos:
    runs-on: ubuntu-latest
    needs: [publish-finalize]
    steps:
      - name: Pull and retrieve version numbers
        uses: actions/checkout@v2
      - name: Export Numbers
        run: |
          export ENGINE_VERSION_NUMBER=$(awk -F '=' '/libVersion=/{print $2}' gradle.properties)
          echo "::set-env name=ENGINE_VERSION::$ENGINE_VERSION_NUMBER"
          export KORGE_VERSION=$(awk -F '=' '/korgeVersion=/{print $2}' gradle.properties)
          echo "::set-env name=KORGE_VERSION::$KORGE_VERSION"
          export KORGE_PLUGIN_VERSION=$(awk -F '=' '/korgePluginVersion=/{print $2}' gradle.properties)
          echo "::set-env name=KORGE_PLUGIN_VERSION::$KORGE_PLUGIN_VERSION"
          export KOTLIN_VERSION=$(awk -F '=' '/kotlinVersion=/{print $2}' gradle.properties)
          echo "::set-env name=KOTLIN_VERSION::$KOTLIN_VERSION"


      - name: Bump version number for Template
        run: |
          sed -i 's/val libEmiVersion=".*/val libEmiVersion="'"$ENGINE_VERSION"'"/g' gradle.properties
          sed -i 's/val korgePluginVersion=".*/val korgePluginVersion="'"KORGE_PLUGIN_VERSION"'"/g' gradle.properties
          git config --global user.email ${{ secrets.gitEmail }}
          git config --global user.name ${{ secrets.gitName }}
          git add build.gradle.kts
          git commit -m "Bumped version number to $ENGINE_VERSION"

      - name: Create PR for Template
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.engineEmiGradlePluginRepoToken }}
          labels: automerge