name: TEST

on:
  pull_request:
  push:
    branches:
      - 'snapshots'

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        - with:
            ref: snapshots
      - run: CALL gradlew.bat --no-daemon jvmTest
        shell: cmd

  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        - with:
            ref: snapshots
      - run: ./gradlew --no-daemon jvmTest

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: snapshots
      - run: ./gradlew --no-daemon jvmTest